### ISSUE TITLE
onOpen and onClose fires on init

### ISSUE THREAD

**Issue by killion** [imgix/luminous#18]
Hi there, we are Imgix customers and are grateful for this lib since we don't use jQuery. We are trying to set it up and are running into an issue. We want to extend Luminous to be a full gallery by using the onOpen and onClose event calls to modify the lightbox. But the events fire when the Luminous is created not when it opens or closes. Here is a demo: http://codepen.io/killion/pen/pyPymJ

Thanks!

**Comment by paulstraw** [comment]
Hey there @killion, thanks for the great example. The reason you're seeing this behavior is because `onOpen` and `onClose` should be passed a function reference. I've edited your CodePen with an example of how this works: http://codepen.io/imgix/pen/zqEQGa

Feel free to reopen this issue if you have more questions!
