### ISSUE TITLE
Add "onChange" parameter for LuminousGallery

### ISSUE THREAD

**Issue by arnofo** [imgix/luminous#48]
Hello,

First of all, thank you for this great library.

As the title says, I do feel like there is one feature missing for the LuminousGallery, which is an "onChange" callback parameter when we navigate to the previous or next Luminous instance.

It would probably be nice if the direction was passed as a parameter to the callback as well.

Thank you very much.

**Comment by frederickfogerty** [comment]
Hey @arnofo 👋 

I'm from Imgix and from today I'm responsible for the maintenance of this library. Currently, we're focussing on bugs and other issues, but I'll be sure to investigate this when we get to improving these libraries! 👍

**Comment by kangw3n** [comment]
Any update on this issue?

I found that `onChange` event is quite useful in some circumstance: 

While images inside a gallery is usually was a full size big image, when switching image, it turns out caption had changed while image still being download, which lack of crucial loading information in term of UX, perharp some misleading image caption.

It would be nice if we can pass a callback to indicate loading or spinner on change hook.

Anyway, this is a great library in overall.

**Comment by sherwinski** [comment]
Hey all, sorry for the silence on this.
I definitely agree that this would be a useful addition to the library. This could also provide a solution to the caption issue @kangw3n mentioned (also discussed in #243). Unfortunately I won't be able to look into this for a while, but would gladly accept a PR if anyone is up for it.
