### ISSUE TITLE
Support a caption or arbitrary markup

### ISSUE THREAD

**Issue by jackmcdade** [imgix/luminous#7]
Is there any way (or plans) to support adding a caption or or some markup to the lightbox declaratively? For example, if i wanted to add `data-title="Pretty flowers"` to my luminous element, I'd love to show that under the lightbox.

**Comment by isaachinman** [comment]
@paulstraw Can you provide an example of how to use captions, given this update? I'm reading through the source code but it's not immediately obvious how you expect users to arrange the markup.

**Comment by paulstraw** [comment]
Hey @isaachinman, sorry this wasn't clear. As stated in the options in the readme:

> Captions can be a literal string, or a function that receives the Luminous instance's trigger element as an argument and returns a string. Supports HTML, so use caution when dealing with user input.

If you have a static string, you can simply do something like `caption: 'hello world'`. If you want to do something more dynamic like pulling the value from an attribute, the `index.html` example you posted above is the approach.

**Comment by isaachinman** [comment]
@paulstraw Yes, thanks. Although I fail to see the use of having something like `caption: 'hello world'`... this would set the same caption for all images in the lightbox, which seems rather contrary to what captions fundamentally are.

Also, there is a significant bug in the caption source code. I took after the `index.html` usage and used the alt attribute of my `img` tags for captions - two birds with one stone.

So: `return trigger.querySelector('img').getAttribute('alt')`.

However, in my application, providing captions is an optional user action, so some photos in the lightboxes may have captions while others may not. If the alt attribute is empty, eg with a value of `''`, strange things start to happen. I assume this is because somewhere in the code base, the truthiness of this caption value is being checked in a very simple way, and an empty string obviously evaluates to false. However this causes "carry-over" of the "default" caption value.

For example, if I had 10 images, and only image 1 and image 5 had captions, the lightbox would display images 1-4 _all having the caption of image 1_, and images 5-10 _all having the caption of image 5_. I can provide a jsfiddle example if this isn't clear.

It should be a very simple PR to fix this, and I would be happy to.

For anyone in the meantime looking for a quick solution, here's one: the caption value is HTML safe, so just pass an empty span instead of an empty string:

    const caption = caption.value ? caption.value : '<span></span>'

Of course this messes with accessibility so it's not a permanent solution.

Cheers for an otherwise fantastic library!

**Comment by paulstraw** [comment]
Ah, that's a great catch @isaachinman. Thanks for the super-thorough report, too! If you want to submit a PR for that, I'd happily merge. If not, I can make that change too. Whichever works for you!

**Comment by paulstraw** [comment]
Oh, and the static captions are really just for the simple case where it's a single image instead of a gallery.

**Comment by isaachinman** [comment]
@paulstraw Sorry, quite busy - so feel free to make the changes yourself. Cheers.
